import { PostItem } from '@/stores/useAppStore';

/**
 * Downloads a post's visual flyer as a high-resolution PNG image.
 * Uses an off-screen HTML5 Canvas to rasterize SVG into a 1080x1350 PNG file.
 */
export async function downloadPostFlyerAsPng(post: PostItem, brandName: string): Promise<boolean> {
  const imageUrl = post.imageUrl;
  if (!imageUrl) return false;

  const sanitizedBrand = (brandName || 'Brand').toLowerCase().replace(/[^a-z0-9]+/g, '-');
  const dayStr = post.dayNumber < 10 ? `0${post.dayNumber}` : `${post.dayNumber}`;
  const filename = `${sanitizedBrand}-day-${dayStr}-flyer.png`;

  try {
    // If it's already a PNG data URL (e.g. from Gemini Imagen API)
    if (imageUrl.startsWith('data:image/png') || imageUrl.startsWith('data:image/jpeg')) {
      triggerDownload(imageUrl, filename);
      return true;
    }

    // If it's an SVG data URL, render it onto a 1080x1350 Canvas for true PNG download
    return new Promise((resolve) => {
      const img = new Image();
      img.crossOrigin = 'anonymous';

      img.onload = () => {
        try {
          const canvas = document.createElement('canvas');
          canvas.width = 1080;
          canvas.height = 1350;
          const ctx = canvas.getContext('2d');
          if (!ctx) {
            triggerDownload(imageUrl, filename);
            return resolve(true);
          }

          ctx.drawImage(img, 0, 0, 1080, 1350);
          const pngUrl = canvas.toDataURL('image/png', 0.95);
          triggerDownload(pngUrl, filename);
          resolve(true);
        } catch (canvasErr) {
          console.warn('Canvas rasterization fallback to direct download:', canvasErr);
          triggerDownload(imageUrl, filename);
          resolve(true);
        }
      };

      img.onerror = () => {
        // Fallback: trigger download directly
        triggerDownload(imageUrl, filename);
        resolve(true);
      };

      img.src = imageUrl;
    });
  } catch (err) {
    console.error('Failed to download visual flyer:', err);
    return false;
  }
}

/**
 * Downloads single post text copy as a text file.
 */
export function downloadPostCopyAsTxt(post: PostItem, brandName: string): void {
  const content = `======================================================
${brandName.toUpperCase()} — DAY ${post.dayNumber} [${post.phase}]
======================================================

PILLAR: ${post.pillar}
POST TYPE: ${post.postType}
OBJECTIVE: ${post.strategicObjective}

------------------------------------------------------
HOOK:
${post.hook}

------------------------------------------------------
CAPTION:
${post.caption}

------------------------------------------------------
CALL TO ACTION (CTA):
${post.cta}

======================================================
Generated by CCS Ultra • Phone-First Creative Intelligence
`;

  const blob = new Blob([content], { type: 'text/plain;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const sanitizedBrand = (brandName || 'Brand').toLowerCase().replace(/[^a-z0-9]+/g, '-');
  const filename = `${sanitizedBrand}-day-${post.dayNumber}-copy.txt`;
  triggerDownload(url, filename);
  URL.revokeObjectURL(url);
}

/**
 * Downloads the full 20-Day Campaign Calendar as a CSV spreadsheet.
 * Compatible with Excel, Google Sheets, Notion, Buffer, and Hootsuite.
 */
export function exportCalendarAsCsv(posts: PostItem[], brandName: string): void {
  const headers = ['Day', 'Phase', 'Pillar', 'Post Type', 'Hook', 'Caption', 'CTA', 'Strategic Objective', 'Visual Status'];

  const rows = posts.map((p) => [
    `Day ${p.dayNumber}`,
    `"${(p.phase || '').replace(/"/g, '""')}"`,
    `"${(p.pillar || '').replace(/"/g, '""')}"`,
    `"${(p.postType || '').replace(/"/g, '""')}"`,
    `"${(p.hook || '').replace(/"/g, '""')}"`,
    `"${(p.caption || '').replace(/"/g, '""')}"`,
    `"${(p.cta || '').replace(/"/g, '""')}"`,
    `"${(p.strategicObjective || '').replace(/"/g, '""')}"`,
    `"${p.visualStatus || 'NOT_GENERATED'}"`,
  ]);

  const csvContent = [headers.join(','), ...rows.map((r) => r.join(','))].join('\n');
  const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
  const url = URL.createObjectURL(blob);
  const sanitizedBrand = (brandName || 'Brand').toLowerCase().replace(/[^a-z0-9]+/g, '-');
  triggerDownload(url, `${sanitizedBrand}-20-day-calendar.csv`);
  URL.revokeObjectURL(url);
}

/**
 * Downloads the full brand strategy playbook and 20-day calendar as a Markdown document.
 */
export function exportCalendarAsMarkdown(
  posts: PostItem[],
  brand: any,
  brandDna: any,
  pricingTiers: any[]
): void {
  const brandName = brand?.name || 'My Brand';
  let md = `# ${brandName} — 20-Day Strategic Content Playbook
*Generated by CCS Ultra • Phone-First Creative Intelligence Engine*

---

## 1. Brand Strategic Foundation
- **Positioning Statement**: "${brandDna?.positioning || brand?.usp || 'Brand Positioning'}"
- **Industry**: ${brand?.industry || 'Commercial Enterprise'}
- **Location**: ${brand?.location || 'Lagos, Nigeria'}
- **Target Audience**: ${brand?.audience || 'General Consumers'}
- **Brand Personality**: ${brandDna?.brandPersonality?.join(', ') || 'Authentic, High-Quality'}

## 2. Colour & Visual Guidelines
- **Recommended Palette**: ${brandDna?.colourSystem?.recommendedPalette?.join(' • ') || '#1E1B4B, #F59E0B'}
- **Aesthetic Mode**: ${brandDna?.visualPersonality?.aestheticMode || 'Editorial Photography'}
- **Photography Direction**: ${brandDna?.photographyDirection || 'Directional natural sunlight'}
- **Negative Constraints (Slop to Avoid)**: ${brandDna?.thingsToAvoid?.join(', ') || 'Purple gradients, glowing neon'}

## 3. Psychological Pricing Strategy
`;

  if (pricingTiers && pricingTiers.length > 0) {
    pricingTiers.forEach((tier) => {
      md += `### ${tier.name} — ${tier.price} ${tier.recommended ? '⭐ [RECOMMENDED OFFER]' : ''}\n`;
      md += `- **Description**: ${tier.description}\n`;
      md += `- **Psychological Hook**: ${tier.psychologicalHook}\n\n`;
    });
  }

  md += `---

## 4. 20-Day Content Matrix (Narrative Arc)

`;

  posts.forEach((p) => {
    md += `### Day ${p.dayNumber < 10 ? `0${p.dayNumber}` : p.dayNumber} — ${p.pillar} [${p.phase}]\n`;
    md += `**Objective**: ${p.strategicObjective}\n\n`;
    md += `**HOOK:**\n> ${p.hook}\n\n`;
    md += `**CAPTION:**\n${p.caption}\n\n`;
    md += `**CALL TO ACTION:**\n\`${p.cta}\`\n\n`;
    md += `---\n\n`;
  });

  const blob = new Blob([md], { type: 'text/markdown;charset=utf-8;' });
  const url = URL.createObjectURL(blob);
  const sanitizedBrand = brandName.toLowerCase().replace(/[^a-z0-9]+/g, '-');
  triggerDownload(url, `${sanitizedBrand}-20-day-playbook.md`);
  URL.revokeObjectURL(url);
}

/**
 * Copies the entire 20-day sequence formatted for WhatsApp Status & Broadcasts.
 */
export function copyFullCalendarForWhatsApp(posts: PostItem[], brandName: string): string {
  return posts
    .map(
      (p) =>
        `*${brandName.toUpperCase()} — DAY ${p.dayNumber < 10 ? `0${p.dayNumber}` : p.dayNumber} [${p.phase}]*\n` +
        `📌 *Pillar:* ${p.pillar}\n\n` +
        `🎯 *HOOK:*\n${p.hook}\n\n` +
        `📝 *CAPTION:*\n${p.caption}\n\n` +
        `👉 *CALL TO ACTION:*\n${p.cta}\n\n` +
        `━━━━━━━━━━━━━━━━━━━━`
    )
    .join('\n\n');
}

/**
 * Downloads all rendered visuals as individual PNG files with staggered delay.
 */
export async function downloadAllFlyersAsPng(posts: PostItem[], brandName: string): Promise<number> {
  const readyPosts = posts.filter((p) => p.visualStatus === 'READY' && p.imageUrl);
  if (readyPosts.length === 0) return 0;

  for (let i = 0; i < readyPosts.length; i++) {
    const post = readyPosts[i];
    await downloadPostFlyerAsPng(post, brandName);
    // 350ms delay between downloads to prevent browser download throttling
    if (i < readyPosts.length - 1) {
      await new Promise((resolve) => setTimeout(resolve, 350));
    }
  }

  return readyPosts.length;
}

/**
 * Helper to trigger a direct file download.
 */
function triggerDownload(url: string, filename: string) {
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
}
